site_name: Augmentare

google_analytics:
  - UA-132343476-2
  - auto

nav:
  - Home: index.md
  - Experiments:
    - CelebA:
      - Summary: experiments/celeba/Bias_CelebA.ipynb
  - GAN methods:
      - DCGAN: api/gan/dcgan.md
  - Style Transfer:
      - Neural Style Transfer: api/style_transfer/nst.md

theme:
  name: "material"
  # logo: assets/x_logo.png
  # favicon: assets/x_logo.png
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - numkdoc
  - search
  - mknotebooks

markdown_extensions:
  - footnotes
  - extra
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - codehilite
  - toc:
      permalink: true
      toc_depth: 1-2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/custom.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/custom.js

repo_name: "deel-ai/augmantare"
repo_url: "https://forge.deel.ai/Fair/augmantare"