site_name: Augmentare

google_analytics:
  - UA-132343476-2
  - auto

nav:
  - Home: index.md
  - Experiments:
    - CelebA:
      - Summary: api/experiments_summary/Bias_CelebA.ipynb
    - EuroSAT:
      - Summary: api/experiments_summary/Bias_EuroSAT.ipynb
  - GAN methods:
      - Deep Convolutional GAN (DCGAN): api/gan/dcgan.md
      - Conditional GAN (CGAN): api/gan/cgan.md
      - Conditional Deep Convolutional GAN (CDCGAN): api/gan/cdcgan.md
      - Cycle GAN: api/gan/cyclegan.md
      - Progressive Growing of GANS (ProGAN): api/gan/progan.md
  - Style Transfer:
      - Fourier Domain Adaptation (FDA): api/style_transfer/fda.md
      - Adaptive Instance Normalization (AdaIN): api/style_transfer/adain.md
      - Neural Neighbor Style Transfer (NNST): api/style_transfer/nnst.md
      - Style Flow: api/style_transfer/styleflow.md
      - Contrastive Coherence Preserving Loss for Versatile Style Transfer (CCPL): api/style_transfer/ccpl.md

theme:
  name: "material"
  logo: assets/aug_logo_wo_bg.png
  favicon: assets/aug_logo_wo_bg.png
  palette:
    - scheme: default
      primary: dark
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - numkdoc
  - search
  - plotly
  - mknotebooks:
      # enable_default_jupyter_cell_styling: false
      # enable_default_pandas_dataframe_styling: false

markdown_extensions:
  - footnotes
  - extra
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - codehilite
  - toc:
      permalink: true
      toc_depth: 1-2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly

extra_css:
  - css/custom.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/custom.js

repo_name: "deel-ai/augmantare"
repo_url: "https://github.com/deel-ai/deel-with-augmentation"